"""data = {
    "name": "Hasip",
    "age": 20,
    "city": "sun francisco" #Access item type data 
}
print(data['city'])

x = data.keys() #keys access type data 
print(x)
c = data.values()
print(c)
print(data.items())
"""

"""
#dictionary access type data 

students = {
    "Name": "Hasip", 
    "age": 20, 
    "university": "Bongobondhu"
}

for items in students: 
    print(items)
for eachitems in students: 
    print(eachitems)
x = students.items()
print(x)
y = students.keys()
print(y)
z = students.values()      #This is dictionary type data  access and modifire
print(z)

"""

Biodata = {
    "Name": "Abid hasan ", 
    "age": 20,  
    "city": "Sanfrancisco"
}

print(Biodata.keys())
print(Biodata.values())
print(Biodata.items())
print(Biodata.pop("age"))

